DECLARE @3MEDICO VARCHAR(20)='PSICOLOGÍA',
        @1FECHAINI DATE='20230101',
        @2FECHAFIN DATE=GETDATE();

SELECT AFI	.PNOMBRE AS PRIMER_NOMBRE,
	   AFI.SNOMBRE AS SEGUNDO_NOMBRE,
	   AFI.PAPELLIDO AS PRIMER_APELLIDO,
	   AFI.SAPELLIDO AS SEGUNDO_APELLIDO,
	   
    AFI.TIPO_DOC,
    AFI.DOCIDAFILIADO,
    TER.RAZONSOCIAL AS ENTIDAD,
    AFI.SEXO as SEXO,
    DATEDIFF(YEAR,AFI.FNACIMIENTO, HCA.FECHA) EDAD,
    AFI.TELEFONORES,
    PLN.TIPOSISTEMA,
    SER.CODCUPS,
    SER.DESCRIPCION_CUPS,

    -- Diagnóstico (IDDx)
    MDX.IDDX,
    MDX.DESCRIPCION AS DESC_DX,
	MDX.CLASIF2 AS GRUPO,

    FORMAT(CIT.FECHAATENCION, 'dd/MM/yyyy') AS FECHAATENCION,

    -- Estado cita
    CASE
        WHEN CIT.CUMPLIDA IN (1, 3) AND MED.IDEMEDICA NOT LIKE '9%' THEN 'Cumplida'
        WHEN MED.IDEMEDICA LIKE '9%' AND FECHALLEGA IS NOT NULL THEN 'Cumplida'
        WHEN CIT.CUMPLIDA NOT IN (1, 3) AND MED.IDEMEDICA NOT LIKE '9%' THEN 'No Asistio'
        WHEN MED.IDEMEDICA LIKE '9%' AND FECHALLEGA IS NULL THEN 'No Asistio'
        ELSE 'No Asistio'
    END AS ESTADO_CITA,

    MED.NOMBRE AS NOMBRE_MEDICO,
    MED.IDMEDICO AS ID_MEDICO,
    MES.IDEMEDICA AS ID_ESPECIALIDAD_MEDICO,
    MES.DESCRIPCION AS ESPECIALIDAD_MEDICA,

    -- Texto clínico desde HCAD
    HCAD.MEMO AS SUBJETIVO,
    HCAD_OBJETIVO.MEMO AS OBJETIVO

FROM CIT
INNER JOIN AFI ON AFI.IDAFILIADO = CIT.IDAFILIADO
INNER JOIN TER ON TER.IDTERCERO = CIT.IDTERCEROCA
INNER JOIN SER ON SER.IDSERVICIO = CIT.IDSERVICIO
INNER JOIN MED ON CIT.IDMEDICO = MED.IDMEDICO
LEFT JOIN MES ON MED.IDEMEDICA = MES.IDEMEDICA
LEFT JOIN HCA ON CIT.CONSECUTIVO = HCA.NOADMISION
              AND CIT.IDAFILIADO = HCA.IDAFILIADO
              AND CIT.IDMEDICO = HCA.IDMEDICO
              AND HCA.PROCEDENCIA = 'IPS'
              AND CAST(HCA.FECHA AS DATE) = CAST(CIT.FECHA AS DATE)
LEFT JOIN MDX ON HCA.IDDX = MDX.IDDX
LEFT JOIN PLN ON CIT.IDPLAN = PLN.IDPLAN
LEFT JOIN CIU ON CIU.CIUDAD = AFI.CIUDAD
LEFT JOIN DEP ON DEP.DPTO = CIU.DPTO

-- JOIN para el campo dinámico de SUBJETIVO
LEFT JOIN HCAD ON HCAD.CONSECUTIVO = HCA.CONSECUTIVO
              AND HCAD.CLASEPLANTILLA = HCA.CLASEPLANTILLA
              AND HCAD.CAMPO = CASE 
                                 WHEN HCA.CLASEPLANTILLA = 'HCPSC_AD' THEN 'C0090'
                                 WHEN HCA.CLASEPLANTILLA = 'HCPSCFV' THEN 'C0090'
                                 WHEN HCA.CLASEPLANTILLA = 'HCPSC_IN' THEN 'C0940'
                                 WHEN HCA.CLASEPLANTILLA = 'HCVALINI' THEN 'C0090'
                               END

-- APPLY para obtener campo C0040 como DATOS_USUARIO
OUTER APPLY (
    SELECT MEMO
    FROM HCAD
    WHERE HCAD.CONSECUTIVO = HCA.CONSECUTIVO
      AND HCAD.CLASEPLANTILLA = HCA.CLASEPLANTILLA
      AND HCAD.CAMPO = CASE 
                         WHEN HCA.CLASEPLANTILLA = 'HCPSC_AD' THEN 'C0100'
                         WHEN HCA.CLASEPLANTILLA = 'HCPSC_IN' THEN 'C0950'
						 WHEN HCA.CLASEPLANTILLA = 'HCPSCFV' THEN 'C0100'
						 WHEN HCA.CLASEPLANTILLA = 'HCVALINI' THEN 'C0100'
                       END
) AS HCAD_OBJETIVO


WHERE
    CIT.FECHA >= @1FECHAINI
    AND CIT.FECHA < DATEADD(DAY, 1, @2FECHAFIN)
    AND (
        MES.DESCRIPCION LIKE @3MEDICO
        OR @3MEDICO = '%'
    )
    AND (
        (CIT.CUMPLIDA IN (1, 3) AND MED.IDEMEDICA NOT LIKE '9%')
        OR (MED.IDEMEDICA LIKE '9%' AND FECHALLEGA IS NOT NULL)
    )
    AND SER.CODCUPS <> '990206'

ORDER BY
    TER.RAZONSOCIAL,
    CIT.FECHA;


